app:
  name: anuglar2-spring-jwt
  itemsPerPage: 10

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.bfwg: DEBUG

